
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


class LandingPage:
    def __init__(self, cleint_page, advisor_page):
        self.OUTPUT_PATH = Path(__file__).parent
        self.ASSETS_PATH = self.OUTPUT_PATH / str(os.path.dirname(os.path.abspath(__file__)) + r"\assets\frame0")
        self.cleint_page = cleint_page
        self.advisor_page = advisor_page

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)
    
    def button_1_hover(self, e):
        self.button_1.config(
            image=self.button_image_hover_1
        )
    def button_1_leave(self, e):
        self.button_1.config(
            image=self.button_image_1
        )

    def button_2_hover(self, e):
        self.button_2.config(
            image=self.button_image_hover_2
        )
    def button_2_leave(self, e):
        self.button_2.config(
            image=self.button_image_2
        )

    def run(self):
        self.window = Tk()
        self.window.title("")

        self.window.geometry("900x600")
        self.window.configure(bg = "#FFFFFF")


        self.canvas = Canvas(
            self.window,
            bg = "#FFFFFF",
            height = 600,
            width = 900,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.button_image_1 = PhotoImage(
            file=self.relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.advisor_page,
            relief="flat"
        )
        self.button_1.place(
            x=312.0,
            y=326.0,
            width=282.0,
            height=74.0
        )

        self.button_image_hover_1 = PhotoImage(
            file=self.relative_to_assets("button_hover_1.png"))

        self.button_1.bind('<Enter>', self.button_1_hover)
        self.button_1.bind('<Leave>', self.button_1_leave)


        self.button_image_2 = PhotoImage(
            file=self.relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=self.cleint_page,
            relief="flat"
        )
        self.button_2.place(
            x=306.0,
            y=434.0,
            width=288.0,
            height=74.0
        )

        self.button_image_hover_2 = PhotoImage(
            file=self.relative_to_assets("button_hover_2.png"))

        self.button_2.bind('<Enter>', self.button_2_hover)
        self.button_2.bind('<Leave>', self.button_2_leave)


        self.canvas.create_text(
            396.0,
            243.0,
            anchor="nw",
            text="Are you a..",
            fill="#000000",
            font=("Poppins Medium", 20 * -1)
        )

        self.canvas.create_text(
            200.0,
            144.0,
            anchor="nw",
            text="LINGUAWEALTH",
            fill="#B40000",
            font=("Poppins Black", 64 * -1, 'bold')
        )

        self.canvas.create_rectangle(
            0.0,
            0.0,
            900.0,
            19.0,
            fill="#B40000",
            outline="")

        self.image_image_1 = PhotoImage(
            file=self.relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            450.0,
            81.0,
            image=self.image_image_1
        )
        self.window.resizable(False, False)
        self.window.mainloop()

    def terminate(self):
        self.window.destroy()
